export interface User {
  id: number;
  first_name: string;
  middle_name?: string;
  last_name: string;
  full_name: string;
  username: string;
  email: string;
  contact_number: string;
  role: 'admin' | 'midwife';
  status: 'pending' | 'approved' | 'rejected' | 'inactive';
  email_verified: boolean;
  barangays: Barangay[];
  last_login?: string;
  created_at: string;
  updated_at: string;
}

export interface Barangay {
  id: number;
  name: string;
  address?: string;
  contact_number?: string;
  barangay_captain?: string;
  health_officer?: string;
  population?: number;
  population_male?: number;
  population_female?: number;
  population_children?: number;
  coverage_area?: string;
  latitude?: number;
  longitude?: number;
  created_at: string;
  updated_at: string;
}

export interface ImmunizationRecord {
  id: number;
  first_name: string;
  middle_name?: string;
  last_name: string;
  full_name: string;
  mother_name?: string;
  father_guardian_name?: string;
  sex: 'Male' | 'Female';
  date_of_birth?: string;
  address?: string;
  barangay_id: number;
  barangay?: Barangay;
  contact_no?: string;
  birth_weight?: number;
  birth_length?: number;
  place_of_birth?: string;
  birth_attendant?: string;
  current_weight?: number;
  current_height?: number;
  head_circumference?: number;
  weight_for_age?: string;
  height_for_age?: string;
  bcg?: string;
  hepa_b?: string;
  dpt1?: string;
  dpt2?: string;
  dpt3?: string;
  opv1?: string;
  opv2?: string;
  opv3?: string;
  measles?: string;
  rotavirus1?: string;
  rotavirus2?: string;
  pcv1?: string;
  pcv2?: string;
  pcv3?: string;
  mmr?: string;
  vit_a_date?: string;
  deworming_date?: string;
  nutritional_status?: string;
  allergies?: string;
  previous_illnesses?: string;
  congenital_abnormalities?: string;
  remarks?: string;
  status: 'active' | 'archived';
  created_by: number;
  creator?: User;
  created_at: string;
  updated_at: string;
}

export interface FamilyPlanningRecord {
  id: number;
  first_name: string;
  middle_name?: string;
  last_name: string;
  full_name: string;
  sex: 'Male' | 'Female';
  age?: number;
  address?: string;
  barangay_id: number;
  barangay?: Barangay;
  civil_status?: string;
  educational_attainment?: string;
  occupation?: string;
  contact_no?: string;
  no_of_living_children?: number;
  partner_name?: string;
  partner_age?: number;
  partner_occupation?: string;
  partner_consent?: 'Yes' | 'No';
  allergies?: string;
  current_medications?: string;
  medical_conditions?: string;
  previous_surgeries?: string;
  last_childbirth_date?: string;
  no_of_miscarriages?: number;
  no_of_stillbirths?: number;
  youngest_child_age?: number;
  blood_pressure?: string;
  weight?: number;
  height?: number;
  bmi?: number;
  smoker?: 'Yes' | 'No';
  history_blood_clots?: 'Yes' | 'No';
  history_cancer?: 'Yes' | 'No';
  history_stroke?: 'Yes' | 'No';
  date_of_visit?: string;
  type_of_client?: string;
  date_accepted?: string;
  type_of_fp_method?: string;
  date_started?: string;
  remarks_side_effects?: string;
  date_of_followup?: string;
  method_changed?: string;
  new_method?: string;
  reason_for_change?: string;
  midwife_name?: string;
  lmp?: string;
  pregnancy_test_result?: string;
  source_of_supply?: string;
  date_of_last_supply?: string;
  quantity_given?: string;
  next_supply_date?: string;
  adherence_notes?: string;
  status: 'active' | 'archived';
  created_by: number;
  creator?: User;
  created_at: string;
  updated_at: string;
}

export interface MaternalCareRecord {
  id: number;
  first_name: string;
  middle_name?: string;
  last_name: string;
  full_name: string;
  age?: number;
  sex: 'Female';
  address?: string;
  barangay_id: number;
  barangay?: Barangay;
  contact_no?: string;
  civil_status?: string;
  educational_attainment?: string;
  occupation?: string;
  gravida?: number;
  para?: number;
  lmp?: string;
  edd?: string;
  blood_type?: string;
  no_of_miscarriages?: number;
  no_of_stillbirths?: number;
  no_of_living_children?: number;
  previous_cesarean?: 'Yes' | 'No';
  previous_complications?: string;
  prenatal_visit_1?: string;
  prenatal_visit_2?: string;
  prenatal_visit_3?: string;
  prenatal_visit_4?: string;
  fundal_height?: string;
  fetal_heart_rate?: string;
  fetal_presentation?: string;
  edema?: string;
  proteinuria?: 'Yes' | 'No';
  weight_monitoring?: string;
  bp_monitoring?: string;
  hemoglobin?: string;
  blood_sugar?: string;
  urinalysis_result?: string;
  ultrasound_date?: string;
  ultrasound_findings?: string;
  has_hypertension?: 'Yes' | 'No';
  has_gestational_diabetes?: 'Yes' | 'No';
  has_multiple_pregnancy?: 'Yes' | 'No';
  has_placenta_previa?: 'Yes' | 'No';
  has_preeclampsia?: 'Yes' | 'No';
  birth_plan?: string;
  preferred_delivery_place?: string;
  emergency_contact?: string;
  emergency_contact_number?: string;
  philhealth_member?: 'Yes' | 'No';
  date_tt1?: string;
  date_tt2?: string;
  date_tt3?: string;
  date_tt4?: string;
  date_tt5?: string;
  fim_status?: string;
  iron_folic?: string;
  calcium?: string;
  iodine?: string;
  bmi?: string;
  deworm?: string;
  syphilis_screening?: string;
  hepa_b_screening?: string;
  hiv_screening?: string;
  date_screened?: string;
  result?: string;
  remarks?: string;
  status: 'active' | 'archived';
  created_by: number;
  creator?: User;
  created_at: string;
  updated_at: string;
}

export interface SeniorCitizenRecord {
  id: number;
  first_name: string;
  middle_name?: string;
  last_name: string;
  full_name: string;
  sex: 'Male' | 'Female';
  age?: number;
  address?: string;
  barangay_id: number;
  barangay?: Barangay;
  contact_no?: string;
  civil_status?: string;
  occupation?: string;
  educational_attainment?: string;
  blood_pressure?: string;
  weight?: number;
  height?: number;
  bmi?: number;
  temperature?: number;
  heart_rate?: number;
  respiratory_rate?: number;
  has_hypertension?: 'Yes' | 'No';
  has_diabetes?: 'Yes' | 'No';
  has_heart_disease?: 'Yes' | 'No';
  has_kidney_disease?: 'Yes' | 'No';
  has_arthritis?: 'Yes' | 'No';
  has_copd_asthma?: 'Yes' | 'No';
  has_dementia?: 'Yes' | 'No';
  maintenance_medications?: string;
  medication_allergies?: string;
  mobility_status?: string;
  adl_score?: string;
  fall_history?: 'Yes' | 'No';
  uses_assistive_device?: string;
  memory_status?: string;
  dementia_screening_result?: string;
  blood_sugar_level?: string;
  cholesterol_level?: string;
  tb_screening?: string;
  cancer_screening?: string;
  living_arrangement?: string;
  primary_caregiver?: string;
  emergency_contact?: string;
  emergency_contact_number?: string;
  nutritional_status?: string;
  special_diet?: 'Yes' | 'No';
  special_diet_details?: string;
  has_dentures?: 'Yes' | 'No';
  last_dental_visit?: string;
  eye_complaints?: string;
  visual_acuity?: string;
  with_eye_problem?: string;
  pinhole_vision_result?: string;
  date_referred?: string;
  management?: string;
  ppv_immunization_date?: string;
  influenza_immunization_date?: string;
  remarks?: string;
  status: 'active' | 'archived';
  created_by: number;
  creator?: User;
  created_at: string;
  updated_at: string;
}

export interface LoginCredentials {
  username_or_email: string;
  password: string;
}

export interface RegisterData {
  first_name: string;
  middle_name?: string;
  last_name: string;
  username: string;
  email: string;
  password: string;
  password_confirmation: string;
  contact_number: string;
  barangays: number[];
}

export interface AuthResponse {
  message: string;
  user: User;
  token: string;
}

export interface ApiError {
  message: string;
  errors?: Record<string, string[]>;
}
